apiVersion: gitlab.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  namespace: example-namespace
spec:
  baseURL: string
  credentials:
    env:
      name: string
    fs:
      path: string
    method: string
    secretRef:
      key: string
      name: string
      namespace: string
    source: "None" # "None", "Secret", "InjectedIdentity", "Environment", "Filesystem"
